name: CI

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - build/**
      - .github/workflows/ci.yml
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - build/**
      - .github/workflows/ci.yml
  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_CONFIG: Release
      SOLUTION: "src/Pdf2Image.sln"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Build Version
        run: |
          Import-Module .\build\Get-BuildVersion.psm1
          Write-Host $Env:GITHUB_REF
          $version = Get-BuildVersion -VersionString $Env:GITHUB_REF
          echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore $SOLUTION

      - name: Build solution
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore
